// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaPLWMAnptLGX7e8EOmTEfvU-w6iwNT3E',
    appId: '1:615869790960:web:964f37cbaa78fccbbd2035',
    messagingSenderId: '615869790960',
    projectId: 'groupchat-57018',
    authDomain: 'groupchat-57018.firebaseapp.com',
    storageBucket: 'groupchat-57018.appspot.com',
    measurementId: 'G-TD9HLJX4B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhrPt9PBfmTqW6IsZSG6cQM9-1LYt6vs8',
    appId: '1:615869790960:android:a67fe5de4c2a741dbd2035',
    messagingSenderId: '615869790960',
    projectId: 'groupchat-57018',
    storageBucket: 'groupchat-57018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYcYYKsl7bxg2cDRkmk6awUe39x9dyndk',
    appId: '1:615869790960:ios:98db18a0558b90d8bd2035',
    messagingSenderId: '615869790960',
    projectId: 'groupchat-57018',
    storageBucket: 'groupchat-57018.appspot.com',
    iosBundleId: 'com.flattrade.groupchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYcYYKsl7bxg2cDRkmk6awUe39x9dyndk',
    appId: '1:615869790960:ios:98db18a0558b90d8bd2035',
    messagingSenderId: '615869790960',
    projectId: 'groupchat-57018',
    storageBucket: 'groupchat-57018.appspot.com',
    iosBundleId: 'com.flattrade.groupchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaPLWMAnptLGX7e8EOmTEfvU-w6iwNT3E',
    appId: '1:615869790960:web:a7eff9aa150eb5e5bd2035',
    messagingSenderId: '615869790960',
    projectId: 'groupchat-57018',
    authDomain: 'groupchat-57018.firebaseapp.com',
    storageBucket: 'groupchat-57018.appspot.com',
    measurementId: 'G-VKWZE8D01B',
  );
}
